name: Workflow 1
"on":
  - push
  - pull_request
jobs:
  workflow1_job1:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - if: ${{ runner.os }} == 'Linux'
        run: |-
          cat <<EOD
          ${{ toJSON(github) }}
          EOD
      - run: |-
          cat <<EOD
          ${{ toJSON(github) }}
          EOD
      - run: |-
          cat <<EOD
          ${{ contains(github.event.head_commit.message, '
          TryBot-Trailer: ') }}
          EOD
