name: Workflow 1
"on":
  - push
  - pull_request
jobs:
  workflow1_job1:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - run: |-
          cat <<EOD
          ${{ toJSON(github) }}
          EOD
      - id: unityTrailer
        run: |-
          x="$(git log -1 --pretty='%(trailers:key=Unity-Trailer,valueonly)')"
          if [ "$x" == "" ]
          then
          	x=null
          fi
          echo "unityTrailer<<EOD" >> $GITHUB_OUTPUT
          echo "$x" >> $GITHUB_OUTPUT
          echo "EOD" >> $GITHUB_OUTPUT
      - if: ${{ fromJSON(steps.unityTrailer.outputs.unityTrailer) == null }}
        run: echo "No trailer set"
      - if: ${{ fromJSON(steps.unityTrailer.outputs.unityTrailer) != null }}
        run: |-
          echo CL is ${{ fromJSON(steps.unityTrailer.outputs.unityTrailer).CL }}
          echo patchset is ${{ fromJSON(steps.unityTrailer.outputs.unityTrailer).patchset }}
      - run: |-
          cat <<EOD | tr '
          ' ' '
          ${{ toJSON(github.event.head_commit.author) }}
          EOD
