name: Workflow 1
"on":
  - push
  - pull_request
jobs:
  workflow1_job1:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - run: |-
          pwd
          cd d:/
          ls
      - uses: actions/setup-go@v4
        with:
          cache: false
          go-version: "1.20"
      - uses: actions/checkout@v3
      - run: go env
      - run: pwd
