name: Workflow 1
"on":
  - push
  - pull_request
jobs:
  workflow1_job1:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - run: |-
          cat <<EOD
          ${{ toJSON(github.event) }}
          EOD
      - if: |-
          contains(github.event.head_commit.message, '
          TryBot-Trailer: {')
        name: No braces
        run: echo No braces matched
      - if: |-
          ${{ contains(github.event.head_commit.message, '
          TryBot-Trailer: {') }}
        name: Braces
        run: echo No braces matched
