name: Workflow 1
"on":
  - push
  - pull_request
jobs:
  workflow1_job1:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - run: |-
          cat <<EOD
          ${{ toJSON(github) }}
          EOD
